[build]
  publish = "."
  functions = "netlify/functions"

# Pretty API routes -> serverless functions
[[redirects]]
  from = "/api/rsvp"
  to = "/.netlify/functions/rsvp"
  status = 200

[[redirects]]
  from = "/api/rsvp-download"
  to = "/.netlify/functions/rsvp-download"
  status = 200
